/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:d438984f-9e89-4f65-a9d1-7ddb5ba753f0",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_lREo4wCZo",
    "aws_user_pools_web_client_id": "558ralabm2jshgc9fv0dludq0h",
    "oauth": {}
};


export default awsmobile;
